# Use a imagem base do PostgreSQL
FROM postgres:13

# Defina variáveis de ambiente para o PostgreSQL
ENV POSTGRES_DB=botecobrasil
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=12345678

# Exponha a porta que o PostgreSQL estará escutando
EXPOSE 5432